AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-billing-notify
  Sample SAM Template for aws-billing-notify

Globals:
  Function:
    Timeout: 5

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Policies:
        - CloudWatchReadOnlyAccess
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 12 * * ? *)
      Environment:
        Variables:
          PARAM1: VALUE
    Metadata:
      DockerTag: v1
      DockerContext: .
      Dockerfile: Dockerfile
