AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: aws-cost-notify

Globals:
  Function:
    Timeout: 5

Resources:
  AwsCostNotifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      # https://docs.aws.amazon.com/ja_jp/IAM/latest/UserGuide/list_awscostexplorerservice.html
      # https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/billing-example-policies.html#example-policy-ce-api
      # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-iam-policy.html
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ce:*'
              Resource: '*'
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 13 * * ? *)
      Environment:
        Variables:
          AWS_PROFILE: default
          LINE_NOTIFY_TOKEN: !Ref LineNotifyToken
          LINE_POST_URL: !Ref LinePostUrl
    Metadata:
      DockerTag: v1
      DockerContext: .
      Dockerfile: Dockerfile

Parameters:
  LineNotifyToken:
    Type: String
  LinePostUrl:
    Type: String