AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: aws-cost-notify

Globals:
  Function:
    Timeout: 5

Resources:
  AwsCostNotifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Policies:
        - CloudWatchReadOnlyAccess
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 12 * * ? *)
      Environment:
        Variables:
          AWS_PROFILE:
          LINE_NOTIFY_TOKEN:
          LINE_POST_URL: "https://notify-api.line.me/api/notify"
    Metadata:
      DockerTag: v1
      DockerContext: .
      Dockerfile: Dockerfile
